name: pax's dev blog
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      header: 
        backgroundImage: /assets/bg/earthrise.jpg
  -
    scope:
      path: "tag"      
    values:
      header: 
        backgroundImage: /assets/bg/soyuz.jpg
