name: pax's dev blog

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      header: 
        backgroundImage: /assets/bg/earthrise.jpg
