name: pax's dev blog
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      header: 
        backgroundImage: /assets/bg/earthrise.jpg
